
import './globals.css'
import Nav from "./components/Nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className=''>
        
        <div className="flex  justify-center bg-white ">
          <div className='max-w-6xl w-full flex '>
          <Nav />
           <div className='flex-2 w-full'>
           {children}
          </div>
          </div>
          
          </div>
       
       
      </body>
      
    </html>
  )
}
